config/routes.rb
Dossier::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'search' => 'pages#search'
  match 'help' => 'pages#help'
  match 'about' => 'pages#about'

  match 'links/:id/vote/:type' => 'links#vote'
  match 'links/:id/click' => 'links#click'
  match 'links/search' => 'links#search'
  match 'links/fetch' => 'links#fetch'
  match 'category/:category' => 'links#category', as: 'category'

  match 'subscribers/newsletter' => 'subscribers#newsletter'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :links do
    resources :comments
  end
  
  resources :subscribers
  resources :users

  root :to => 'links#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :picture, :provider, :uid

  has_many :links
  has_many :comments

  def self.from_omniauth(auth)
    auth["uid"] = auth["uid"].to_s
    where(auth.slice("provider", "uid")).first || create_from_omniauth(auth)
  end

  def self.create_from_omniauth(auth)
    pp auth
    if auth["extra"]["accounts"].any? { |a| a[:name] == 'roundhouse' }
      create! do |user|
        user.provider = auth["provider"]
        user.uid = auth["uid"].to_s
        user.name = auth["info"]["name"]
        user.email = auth["info"]["email"]
        user.picture = self.get_picture(auth)
      end
    end
  end

  def self.get_picture(auth)
    account_id = nil

    auth["extra"]["accounts"].each do |a|
      if a["product"] == "bcx"
        account_id = a["id"].to_s
      end
    end

    url = JSON.parse(open('https://basecamp.com/'+account_id+'/api/v1/people/me.json?access_token='+auth["credentials"]["token"]).read)['avatar_url'].gsub('avatar.gif', 'avatar.96.gif')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @recent_comments = Comment.where(:user_id => @user.id).limit(3)

    add_breadcrumb @user.name, user_path(@user)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_single.html.erb
<article class="user">
  <aside class="profile">

    <h2><%= image_tag user.picture, {:width => 70, :height => 70} %> <%= user.name %> <span> <%= mail_to user.email, user.email, :encode => "hex" %></span></h2>
  </aside>

  <h3>Recent comments</h3>

  <div id="comments">
    <% if @recent_comments.count %>
      <% @recent_comments.each do |comment| %>
        <% @link = Link.find_by_id(comment.commentable_id) %>
        <h4>Posted on: <%= link_to @link.title, link_path(@link) %></h4>
        <%= render 'comments/single', :comment => comment %>
      <% end %>
    <% else %>
      <p>No comments yet.</p>
    <% end %>
  </div>

  <div id="user-submitted-links">
    <h3><%= pluralize(user.links.count, 'link') %> submitted</h3>
  </div>
</article>

<% user.links.each do |link| %>
  <%= render 'links/single', :link => link %>
<% end %>

app/views/users/show.html.erb
<%= render 'single', :user => @user %>