config/routes.rb
Dossier::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'search' => 'pages#search'
  match 'help' => 'pages#help'
  match 'about' => 'pages#about'

  match 'links/:id/vote/:type' => 'links#vote'
  match 'links/:id/click' => 'links#click'
  match 'links/search' => 'links#search'
  match 'links/fetch' => 'links#fetch'
  match 'category/:category' => 'links#category', as: 'category'

  match 'subscribers/newsletter' => 'subscribers#newsletter'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :links do
    resources :comments
  end
  
  resources :subscribers
  resources :users

  root :to => 'links#index'

end

app/models/link.rb
class Link < ActiveRecord::Base
  attr_accessible :category_id, :click_count, :body, :title, :url, :vote_count, :user_id

  has_time_span_scopes
  
  belongs_to :category
  belongs_to :user
  has_many :comments, as: :commentable

  before_create :set_default_values

  validates :url, :presence => true, :uniqueness => true, :format => {:with => URI::regexp(%w(http https))}
  validates :title, :presence => true

  self.per_page = 30

  def set_default_values
    self.vote_count ||= 0
    self.click_count ||= 0
  end

  def vote(type)
    if type == 'down'
      self.vote_count -= 1
    else
      self.vote_count += 1
    end
  end

  def click
    self.increment!(:click_count)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  add_breadcrumb "Home", :root_path

  # GET /links
  # GET /links.json
  def index
    @links = Link.order('created_at DESC').paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    @link = Link.find(params[:id])
    @commentable = @link
    @comments = @commentable.comments
    @comment = Comment.new

    add_breadcrumb @link.title, link_path(@link)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @link }
    end
  end

  def search
    query = params[:q].to_s

    if query
      @links = Link.search(query).paginate(:page => params[:page])
    end

    add_breadcrumb "Search results for '#{query}'", root_path

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @links }
    end
  end

  def category
    @category = params[:category].capitalize
    @links = Link.order('created_at DESC').where(:categories => {:title => @category}).joins(:category).paginate(:page => params[:page])

    add_breadcrumb @category, category_path(@category)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @links }
    end
  end

  # GET /links/new
  # GET /links/new.json
  def new
    @link = Link.new
    @query_url = params[:url]
    @query_title = params[:title]

    add_breadcrumb "New Link", new_link_path(@link)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  # GET /links/1/edit
  def edit
    @link = Link.find(params[:id])

    add_breadcrumb "Edit Link", edit_link_path(@link)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @link }
    end
  end

  def vote
    @link = Link.find(params[:id])
    @link.vote params[:type]
    @link.save

    respond_to do |format|
      format.html  { render json: @link.vote_count, content_type: 'application/json' }
    end
  end

  def click
    @link = Link.find(params[:id])
    @link.click
    @link.save

    respond_to do |format|
      format.json { render json: @link }
    end
  end

  def fetch
    biff = Biffbot::Base.new(APP_CONFIG["diffbot"])
    @res = biff.parse params[:url], {:summary => false, :comments => false}

    respond_to do |format|
      format.json { render json: @res }
    end
  end

  # POST /links
  # POST /links.json
  def create
    @link = Link.new(params[:link])

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link was successfully created.' }
        format.json { render json: @link, status: :created, location: @link }
      else
        format.html { render action: "new", notice: 'Sorry, that entry is a duplicate.' }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /links/1
  # PUT /links/1.json
  def update
    @link = Link.find(params[:id])

    respond_to do |format|
      if @link.update_attributes(params[:link])
        format.html { redirect_to @link, notice: 'Link was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link = Link.find(params[:id])
    if current_user == @link.user
      @link.destroy
    end

    respond_to do |format|
      format.html { redirect_to links_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/links_helper.rb
module LinksHelper
  def url_format(url)
    host = URI.parse(url).host
    if host
      host.gsub('www.', '')
    end
  end

  def embed_media(url)
    allowed = /img|iframe/
    res = auto_html(url) {html_escape; image; youtube(:width => '100%', :height => '400px'); vimeo(:width => '100%', :height => '400px'); soundcloud; twitter; simple_format}

    if res =~ allowed
      res
    else
      false
    end
  end
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h3><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved. Please try again.</h3>

      <ul>
      <% @link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %>
    <%= f.text_field :url, :placeholder => 'Please include the whole thing', :value => @query_url %>
  </div>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :placeholder => 'Use whatever you see fit', :value => @query_title %>
  </div>

  <div class="field">
    <%= f.label :category, 'Category' %>
    <%= collection_select(:link, :category_id, Category.all, :id, :title) %>
  </div>

  <div class="field">
    <%= f.label :body, 'Body <span>*HTML allowed</span>'.html_safe %>
    <%= f.text_area :body %>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/links/_links.html.erb
<% @links.each do |link| %>
  <%= render 'single', :link => link %>
<% end %>

<%= will_paginate @links %>

app/views/links/_single.html.erb
<article class="link" data-url="<%= link.url %>" data-id="<%= link.id %>">
  <div class="vote-buttons">
    <a href="/links/<%= link.id %>/vote/up" class="arrow-up"></a>
    <div class="vote-count">
      <%= link.vote_count %>
    </div>
  </div>

  <h2><%= link_to link.title, link.url, "data-url" => link.url, "data-link-id" => link.id, :class => "track-count" %> <span> &mdash; <%= link_to link.category.title, category_path(link.category.title) %></span></h2>
  
  <% unless link.body.empty? %>
    <p><%= link.body.html_safe %></p>
  <% end %>

  <% if embed_media(link.url) %>
    <div class="media">
      <% if params[:action] == 'show' && params[:controller] == 'links' %>
        <%= embed_media(link.url) %>
      <% else %>
        <script>
        var link_<%= link.id %>_embed_html = '<%= j embed_media(link.url) %>';
        </script>

        <a href="#" class="show-media" data-id="<%= link.id %>">Show media</a>
        <div class="media-content"></div>
      <% end %>
    </div>
  <% end %>
  
  <div class="info">
    <div class="info-data">
      <%= time_ago_in_words(link.created_at) %> ago /&nbsp;
    </div>

    <div class="info-data">
      <%= url_format(link.url) %> /&nbsp;
    </div>

    <div class="info-data">
      <%= link_to pluralize(link.comments.count, 'comment'), link_path(link, :anchor => 'comments') %> /&nbsp;
    </div>

    <div class="info-data">
      by <%= link_to link.user.name, user_path(link.user) %>
    </div>

    <% if current_user == link.user %>
      <div class="info-data">
        &nbsp;/&nbsp;<%= link_to 'delete', link_path(link), :confirm => 'Are you sure?', :method => :delete %> <!-- &nbsp;/&nbsp;<%= link_to 'edit', edit_link_path(link) %> -->
      </div>   
    <% end %>
  </div>

  <% if params[:action] == 'show' && params[:controller] == 'links' %>
    <% if current_user %>
      <%= render 'comments/comments' %>
      <%= render 'comments/form' %>
    <% else %>
      <p>You must be <%= link_to "signed in", "/auth/37signals" %> to post a comment.</p>
    <% end %>
  <% end %>
</article>

app/views/links/category.html.erb
<%= render 'links' %>

app/views/links/edit.html.erb
<div class="page">
  <h2>Edit link</h2>
  
  <%= render 'form' %>
</div>

app/views/links/index.html.erb
<%= render 'links' %>

app/views/links/new.html.erb
<div class="page">
  <h2>Submit a new link</h2>

  <% if current_user %>
    <%= render 'form' %>
  <% else %>
    <p>You must have a Roundhouse Basecamp account and <%= link_to "sign in", "/auth/37signals" %> before submitting a link.</p>
  <% end %>
</div>

app/views/links/search.html.erb
<% unless @links.empty? %>
  <%= render 'links' %>
<% else %>
  <div class="page">
    <h2>Sorry, no results. <%= link_to 'Try again?', search_path %></h2>
  </div>
<% end %>

app/views/links/show.html.erb
<%= render 'single', :link => @link %>