config/routes.rb
Dossier::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'search' => 'pages#search'
  match 'help' => 'pages#help'
  match 'about' => 'pages#about'

  match 'links/:id/vote/:type' => 'links#vote'
  match 'links/:id/click' => 'links#click'
  match 'links/search' => 'links#search'
  match 'links/fetch' => 'links#fetch'
  match 'category/:category' => 'links#category', as: 'category'

  match 'subscribers/newsletter' => 'subscribers#newsletter'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :links do
    resources :comments
  end
  
  resources :subscribers
  resources :users

  root :to => 'links#index'

end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  attr_accessible :email, :frequency

  before_create :set_default_values

  def set_default_values
    self.frequency ||= 'weekly'
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
    add_breadcrumb "Home", :root_path

  # GET /subscribers
  # GET /subscribers.json
  def index
    @subscribers = Subscriber.order('created_at DESC').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @subscribers }
    end
  end

  # GET /subscribers/1
  # GET /subscribers/1.json
  def show
    @subscriber = Subscriber.find(params[:id])

    add_breadcrumb @subscriber.email, subscriber_path(@subscriber)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/new
  # GET /subscribers/new.json
  def new
    @subscriber = Subscriber.new

    add_breadcrumb "Subscribe", new_subscriber_path(@subscriber)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @subscriber }
    end
  end

  # GET /subscribers/1/edit
  def edit
    @subscriber = Subscriber.find(params[:id])
  end

  # POST /subscribers
  # POST /subscribers.json
  def create
    @subscriber = Subscriber.new(params[:subscriber])

    respond_to do |format|
      if @subscriber.save
        format.html { redirect_to root_path, notice: 'Successfully subscribed!' }
        format.json { render json: @subscriber, status: :created, location: @subscriber }
      else
        format.html { render action: "new" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /subscribers/1
  # PUT /subscribers/1.json
  def update
    @subscriber = Subscriber.find(params[:id])

    respond_to do |format|
      if @subscriber.update_attributes(params[:subscriber])
        format.html { redirect_to @subscriber, notice: 'Subscriber was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @subscriber.errors, status: :unprocessable_entity }
      end
    end
  end

  def newsletter
    @subscribers = Subscriber.span('this week')

    pp @subscribers

    LinkMailer.weekly_newsletter(@subscribers, 'hello@joshellington.com').deliver

    redirect_to root_path
  end

  # DELETE /subscribers/1
  # DELETE /subscribers/1.json
  def destroy
    @subscriber = Subscriber.find(params[:id])
    @subscriber.destroy

    respond_to do |format|
      format.html { redirect_to subscribers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/views/subscribers/_form.html.erb
<%= form_for(@subscriber) do |f| %>
  <% if @subscriber.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subscriber.errors.count, "error") %> prohibited this subscriber from being saved:</h2>

      <ul>
      <% @subscriber.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :frequency %>
    <%= f.text_field :frequency %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/subscribers/edit.html.erb
<h1>Editing subscriber</h1>

<%= render 'form' %>

<%= link_to 'Show', @subscriber %> |
<%= link_to 'Back', subscribers_path %>

app/views/subscribers/index.html.erb
<h1>Listing subscribers</h1>

<table>
  <tr>
    <th>Email</th>
    <th>Type</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @subscribers.each do |subscriber| %>
  <tr>
    <td><%= subscriber.email %></td>
    <td><%= subscriber.type %></td>
    <td><%= link_to 'Show', subscriber %></td>
    <td><%= link_to 'Edit', edit_subscriber_path(subscriber) %></td>
    <td><%= link_to 'Destroy', subscriber, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Subscriber', new_subscriber_path %>

app/views/subscribers/new.html.erb
<div class="page">
  <h2>Subscribe now to receive updates in your inbox</h2>
  <small>We promise we'll never use your email for anything but updates.</small>

  <%= render 'form' %>
</div>

app/views/subscribers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @subscriber.email %>
</p>

<p>
  <b>Type:</b>
  <%= @subscriber.frequency %>
</p>


<%= link_to 'Edit', edit_subscriber_path(@subscriber) %> |
<%= link_to 'Back', subscribers_path %>