config/routes.rb
Dossier::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  match 'search' => 'pages#search'
  match 'help' => 'pages#help'
  match 'about' => 'pages#about'

  match 'links/:id/vote/:type' => 'links#vote'
  match 'links/:id/click' => 'links#click'
  match 'links/search' => 'links#search'
  match 'links/fetch' => 'links#fetch'
  match 'category/:category' => 'links#category', as: 'category'

  match 'subscribers/newsletter' => 'subscribers#newsletter'

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

  resources :links do
    resources :comments
  end
  
  resources :subscribers
  resources :users

  root :to => 'links#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dossier</title>
  <link href='http://fonts.googleapis.com/css?family=Karla:400,700' rel='stylesheet' type='text/css'>
  <meta name="viewport" content="width=device-width">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <div class="search-form">
    <form action="/links/search" method="get">
      <div class="container">
        <%= text_field_tag :q, nil, :placeholder => "Type your keywords..." %>
      </div>
      <%= submit_tag 'Go', :name => nil, :class => 'hidden' %>
    </form>
  </div>

  <div class="container">
    <h1><%= link_to 'Dossier', root_path %></h1>

    <nav>
      <%= link_to 'New Link', new_link_path %>
      <!-- <%= link_to 'Subscribe', new_subscriber_path %> -->
      <%= link_to 'Search', search_path, :id => 'open-search-form' %>
      <% if current_user %>
        <%= link_to signout_path do %>
          Sign out
        <% end %>
      <% else %>
        <%= link_to "Sign in", "/auth/37signals" %>
      <% end %>
    </nav>
  </div>
</header>

<% if notice %>
  <div class="container">
    <p id="notice"><%= notice %></p>
  </div>
<% end %>

<nav class="breadcrumb">
  <div class="container">
    <p><%= render_breadcrumbs :separator => ' / ' %></p>
  </div>
</nav>

<div class="container">

  <%= yield %>

  <footer>
    <p style="float:left;"><%= link_to 'Help', help_path %></p>
    <p style="float:right;">Brought to you by the good folks at <a href="http://roundhouseagency.com">Roundhouse</a></p>
  </footer>
</div>


<script type="text/javascript">
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'the-doss'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function () {
    var s = document.createElement('script'); s.async = true;
    s.type = 'text/javascript';
    s.src = 'http://' + disqus_shortname + '.disqus.com/count.js';
    (document.getElementsByTagName('HEAD')[0] || document.getElementsByTagName('BODY')[0]).appendChild(s);
}());
</script>
</body>
</html>